### ISSUE TITLE
Using JitLibExtensions GUIs without SCide but not headless

### ISSUE THREAD

**Issue by gilfuser** [supercollider-quarks/JITLibExtensions#19]
Hi there!

This is not a bug, it's actually the solution. Maybe someone looking for it will find this. Or this could be documented somewhere more official.

It haven't been possible to use JITLibExtensions GUIs (and also adclib and Influx) in other ides other than scide since all the GUI stuff went to `scide_scqt/GUI`. I have been using scide and scnvim interchangeably, and I though the solution to have the GUIs in scnvim should be complicated. It happens that it's something really simple to solve (or should we say 'workaround'?). David Granström just told me how [here](https://github.com/davidgranstrom/scnvim/issues/109): one just have to explicitly include the absolute path to `scide_scqt/GUI` in sclang_conf.yaml.

**Comment by jamshark70** [comment]
OK, I've written about three messages about this now, and further research invalidated them all.

So for now I'm sticking with this question --

Why were the GUI classes moved into scide_scqt/GUI?

AFAIK, the only reasons why it would be necessary to compile GUI-related classes conditionally is:

- Declaring a subclass of a GUI class that doesn't exist in headless systems, or
- Defining `+ TheClass` extension methods of a GUI class that doesn't exist in headless systems.

As far as I can see, JITLibExtensions is doing neither of these things. So the practical effect of the move is to make it difficult for Emacs and vim users to install this quark.

I can't find any documentation of specific errors that were encountered in headless systems. It seems unlikely to me that this was done in the absence of specific errors, but there's no paper trail either.

We should work toward a situation where IDE, Qt-but-non-IDE *and* headless environments are all cleanly supported. This might require new sclang features, or it might not. But the current situation is not correct. The classes in question are not related to the IDE so they have no business being tied to the IDE.

**Comment by adcxyz** [comment]
Hi @jamshark70, 

I believe the criteria need to include 
- Classes that use any View subclasses or composites of View subclasses (e.g. EZGui)

Strangely, non-existing classes in class files do compile, 
but post an execution warning when used: 
```
MyTest { 
	*bingoTest { ^[ Bingo, Bongo.play ] }
}

MyTest.bingoTest

Execution warning: Class 'Bingo' not found
Execution warning: Class 'Bongo' not found
-> [ nil, nil ]
```
So I think it makes sense to exclude those View-using classes/methods on headless systems too. 
If you rough-test for these, there are more cases:

```
~classes = List[];
(View.allSubclasses ++ EZGui.allSubclasses).do { |cl| 
	Class.findAllReferences(cl.name).do { |method|
		var class = method.ownerClass;
		if (method.filenameSymbol.asString.containsi("jitlibextensions")) { 
			if (~classes.includes(class).not) { 
				~classes.add(class.postln).postln
			}
		}
	}
};
~classes;

-> List[ class ProxyChainGui, class ProxyMixer, class ProxyPresetGui, class RecordProxyMixer2, class PrePostView, class ProxyPreset, class ParamGui, class EnvirGui, class StoredList ]
```

**Comment by jamshark70** [comment]
My thinking is:

- If you put the GUI classes in an IDE directory, then you can't use the GUI classes *at all* except if you are using the specific IDE (unless the user hacks it by symlinking or copying -- but I don't think we should be satisfied with "eh, you're using emacs so you have to do some extra messing about"). The classes have nothing to do with the IDE, so why is their usage tied to an editor? (That is, the editor directory is related to but orthogonal to the needed feature -- so, it's not the right solution. That's why I'm asking why this was done. If the wrong solution is to be used, the need for it should be critical. This hasn't been established.)

- If you install the files even though they refer to features that may not be supported, you get a runtime error but everything else is working.

So the current situation is: to prevent *some* users from encountering runtime errors, these features are removed from *every* user of *every* other editor. I don't think this is a fair trade. The cost to the (presumably) larger number of non-IDE users is more significant than the benefit to the (smaller) number of headless system users.

**Comment by adcxyz** [comment]
Hi James, 
completely agreed - I did not understand the independence of front ends and QtGUI well enough; 
since SC does not yet support separate selective-compile folder names for QtGUI alone, 
I was under the impression that moving GUIs to scide_scqt was the corrrect way.

So do you propose to just move them back?
Into folders called GUI, so they can be excluded by hand on headless systems?
And ask for a new SC feature, selective compilation of "GUI" folders only when Qt is present?

**Comment by jamshark70** [comment]
It is confusing -- since the folder name mentions qt, it does seem at first like that would be right.

Overnight, I realized that the current case can probably be handled without a new sclang feature (assuming that nothing in JITLibExtensions subclasses or adds extension methods to core views):

- Move the GUI folder outside of scide_scqt.
- In one of the classes in this folder, add an `*initClass` containing something like `if('View'.asClass.isNil) ...` and the true branch would:
  ``` 
  LanguageConfig.addExcludePath(this.filenameSymbol.asString.dirname);
  thisProcess.recompile;
  ```

Users of Qt enabled installations would see nothing odd.

Users of headless systems would see the class library compile twice, but only the first time after installing the quark. After that, the `View` check would be excluded, and never run again.

Extending or subclassing Views would require new logic in sclang (because library compilation would fail, so a class definition would never have the chance to deal with it).

**Comment by adcxyz** [comment]
Hm, I have the same situation in 5 currently installed quarks already, 
so placing your fix in every quark seems suboptimal. 

For cases which extend or subclass Views, one would have to look 
into a quark path before or while installing it, and if Platform.hasQt.not, 
exclude the GUI folder paths while installing the quark path. 
 
For discussion, this script catches all simple GUI folders 
(like the one in JITLibExtensions), so something like it 
could be recommended to headless system users:
```
// Systems without Qt should exclude all GUI folders.
// This script assumes that Quark authors follow the convention
// of putting all GUI/Qt-dependent classes and methods
// in a folder called ...<somewhere>/GUI".

// If you use a qt-less system, run this function once 
// to exclude all GUI folders in already installed quarks:
(
~excludeGuiFolders = { 
	"... this platform has no Qt, so excluding all GUI class folders:".postln;
	~guiFilenames = Class.allClasses.collectAs(_.filenameSymbol, Set).select { |flnm|
		flnm.asString.containsi("/GUI/")
	}.as(SortedList); 
	"% ~guiFilenames found.\n".postf(~guiFilenames.size); 
	// 	~guiFilenames.printAll; "";
	
	~guiFolders = ~guiFilenames.collect { |flnm| 
		flnm.asString.keep(flnm.asString.find("/GUI/") + 4).asSymbol 
	}.asSet.as(SortedList); 
	"% ~guiFolders found.\n".postf(~guiFolders.size); 
	// ~guiFolders.printAll; "";
	"*** EXCLUDING: ".postln;
	~guiFolders.do { |guifolder|
		LanguageConfig.addExcludePath(guifolder.postcs);
	};
	LanguageConfig.store;
};

if (Platform.hasQt) { 
	~excludeGuiFolders.value;
	this.recompile;
};
)
```

**Comment by adcxyz** [comment]
OK, I moved the GUI folder back outside the scide_scqt folder. 
headless system users will have to exclude it by hand if needed.

**Comment by adcxyz** [comment]
... sorry, had lost track of this - now the folder really are moved back!
