### ISSUE TITLE
MainFXGui ignores specs from NamedControl

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider-quarks/JITLibExtensions#22]
Hi ! Stumbled on a small issue when using NamedControl style specs/arguments with the ProxyChain/MainFXGui classes. The specs are ignored unless input in the specs argument explicitly:

```supercollider
// Does not work:
ProxyChain.add3(
    srcName: \jpverb, 
	source: \filter -> { |in| 
		JPverb.ar(
			in: in,  
			t60: \time.kr(10, spec: [0.0001,100.0,\exp]),  
		);
	}
);

// Does work:
ProxyChain.add3(
    srcName: \jpverb, 
	source: \filter -> { |in| 
		JPverb.ar(
			in: in,  
			t60: \time.kr(10),  
		);
	},
    specs: (time: [0.0001,100.0,\exp])
)
```

**Comment by LFSaw** [comment]
another reproducer:

```
Ndef(\foo, { 
	SinOsc.ar(\freq.kr(spec:ControlSpec(200, 20000))) 
});

// specs are stored in specs variable
Ndef(\foo).specs

// but this (used in all NodeProxy-related stuff) returns default spec, resp. a spec defined in the Halo
Ndef(\foo).getSpec(\freq)

// hence, this does not know about the spec
Ndef(\foo).edit
```

any ideas?

I'm happy to help

**Comment by bgola** [comment]
I was taking a look at this and the issue seems to be when `getSpec` is called, it will try to find an spec using `Halo`, and if it doesn't find it will fallback to the global specs by doing `name.asSpec`.

When `NamedControls` are used the `NamedControl` class has no access to the proxy so can't add the spec to its Halo. It uses UGen.buildSynthDef to add itself to the `SynthDef.specs` array, which is ignored by `getSpec` (which is used for building GUIs and so on). Checking the `this.specs` array before fallback to the global specs would fix that:

```
        getSpec { |name|
		var spec;
		var specs = Halo.at(this, \spec);
		if (name.isNil) { ^specs };
		if (specs.notNil) { spec = specs.at(name) };
		if (spec.isNil and: { name == '#' }) {
			name = this.key;
			if (specs.notNil) { spec = specs.at(name) };
		};
		^spec ?? { this.specs.at(name) ?? { name.asSpec } }
	}
```

Hope this makes sense / help :)

**Comment by LFSaw** [comment]
Thanks, Bruno!

Do we need to implement this only for `Object` or also for other Classes?
It is a little difficult to understand where what is used...

also, since not all objects that support Halo also have a `spec` method, I'd propose

```
+ Object {
        getSpec { |name|
		var spec;
		var specs = Halo.at(this, \spec);
		if (name.isNil) { ^specs };
		if (specs.notNil) { spec = specs.at(name) };
		if (spec.isNil and: { name == '#' }) {
			name = this.key;
			if (specs.notNil) { spec = specs.at(name) };
		};
		if (this.respondsTo(\specs), {
			^spec ?? { this.specs.at(name) ?? { name.asSpec } }
		}, {
			^spec ?? { name.asSpec }
		})
	}
}
```


--------------


Additionally, the question is really, if we need two concurrent implementations for specs anyhow...

**Comment by bgola** [comment]
Definitely it is a bit confusing both `.specs` and `.getSpec`, they are used in different scenarios apparently. `.specs` is defined in `SynthDef` (so mainstream SC code) and `.getSpec` is `JITLibExtensions` stuff... I guess the right approach, as it is implemented now, is that JITLib takes care of using "official" SC stuff in the back. And probably we should add some explanation to the docs somehow :)

From what I can see simply implementing it for `Object` is enough.

**Comment by LFSaw** [comment]
my proposal would be to remove the 'Halo' implementation of spec handling in favour of mainstream SC but keep backwards compatibility by changing the impelemtation of 'getSpec' and 'addSpec' to use 'specs(_)' internally.

@adcxyz what do you think?

**Comment by adcxyz** [comment]
Hm, 
I am not entirely sure that addSpec and getSpec can be moved transparently to use .specs instead of Halo. 
would be good to sketch it and see if anything breaks.

**Comment by adcxyz** [comment]
the other option would be to add inline-defined specs to the tree that getSpec currently uses.

**Comment by bgola** [comment]
> Hm, I am not entirely sure that addSpec and getSpec can be moved transparently to use .specs instead of Halo. would be good to sketch it and see if anything breaks.

@adcxyz you are right, it seems like in this current implementation anything can have specs using addSpec and getSpec (and storing them in Halo), so changing that would break things (unless we would store specs in Object instead.. but I don't think that makes it much better?)

Maybe we need to think a bit on how to deal with this conflict between original specs dict (taken care by the synthDef builder) and Halo specs.  They are essentially two different things with the same name and dealing with the same domain right now. And the problem is not only with NamedControls, but this also looks wrong and confusing to me:

```supercollider
n = NodeProxy.control(s,1);
n.addSpec(\x, [0,1]);
n.specs.postln; // No specs
// (  )  
Halo.at(n, \spec).postln; // But Halo specs
// ( 'x': a ControlSpec(0, 1, 'linear', 0.0, 0, "") )
n.getSpec(\x)
// a ControlSpec(0, 1, 'linear', 0.0, 0, "")
n.source = {\y.kr(0, spec:[0,10])}
n.specs.postln // some specs
// ( 'y': a ControlSpec(0, 10, 'linear', 0.0, 0, "") )
Halo.at(n, \spec).postln; // some Halo specs
// ( 'x': a ControlSpec(0, 1, 'linear', 0.0, 0, "") )
```

NodeProxy also uses the original specs dict, but JITLib source code even suggests to use the JITLibExtensions quark if you are using specs attached to proxies (see https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/JITLib/GUI/EnvirGui.sc#L327 )

As @LFSaw I wanted to suggest to remove the Halo spec implementation, but it seems like it could break a lot of things. Could be a better option to propose a better Object spec interface in upstream SC code, and then drop the Halo implementation.

For now maybe the best option here is to make sure that the Halo spec implementation is aware of the `specs` dict in case some object implements it (NodeProxy acceses it via SynthDefControl / ProxyInterface -> SynthDef.specs) and will take care of updating itself accordingly to what is in `.specs`.

> the other option would be to add inline-defined specs to the tree that getSpec currently uses.

this would be dealt with if Halo is responsible for syncing .specs to its own specs dict. Not sure what would be the best solution here..

Now, the example I gave above would still be strange even if Halo updates itself, because I can't think of a consistent way for Halo to update the original `.specs` dictionary.  I don't even think it makes sense in the current architecture. So another question is, should addSpec also add the spec to the `specs` dictionary if it exists?  It is very complicated in the case of NodeProxy because `.specs` is a method that returns a collection of all `.objects` specs (all of its synthdef specs), so there is not one exact dict to add the spec in that case.

Anyway, at least to fix the NamedControl behavior for now, I would suggest to apply fix to `.getSpec` as we proposed above (fallback to .spec in case it can't find the spec in Halo).

**Comment by adcxyz** [comment]
PR #36 proposes a fix with a clear precedence order, 
which allows using both styles, and ho to switch between them.

@bgola @LFSaw @madskjeldgaard, please check if you see any issues!

```
// try orig test case:
ProxyChain.add3(
    srcName: \jpverb,
	source: \filter -> { |in|
		JPverb.ar(
			in: in,
			t60: \time.kr(10, spec: [0.0001,100.0,\exp]),
		);
	}
);

// gui uses 0.001 to 100, so all seems well!
MainFX(s).add(\jpverb, 0.1).gui;
```

**Comment by adcxyz** [comment]
Dear @LFSaw, 
since you also use implicit specs a lot, please have a look how well this PR addresses your concerns :-)

**Comment by LFSaw** [comment]
Thanks for the work! see my comment here: https://github.com/supercollider-quarks/JITLibExtensions/pull/36#issuecomment-2563566632
